### ISSUE TITLE
Change color of wave

### ISSUE THREAD

**Issue by sharunspi** [ashiishme/react-sine-wave#2]
Option to change color of wave.
1. Color picker to select 2 colors
2. Opacity low button so that user will not miss the button.
3. Configuration to hide the button if   needed 

**New Concept**

- A button to generate random color.
- User press the button, the color changes.
- One wave will have full alpha, another wave will have slightly less but the same color so that we don't have to create 2 buttons.

**Comment by ashiishme** [comment]
Thank you @sharunspi for your feature request. Are you willing to add color option? Please let me know if you are interested to contribute.

I have attached my concept below:
- A button to generate random color.
- User press the button, the color changes.
- One wave will have full alpha, another wave will have slightly less but the same color so that we don't have to create 2 buttons.

A custom entry filed for color values if users wants to set their color of choice. ( Without color picker ).

Let me know what do you think about this?

**Comment by sharunspi** [comment]
Thanks,
Yes, Your concept is good and I love to do the feature.

**Comment by ashiishme** [comment]
Great, please send a PR once you implement it.

**Comment by ashiishme** [comment]
@sharunspi Any progress?

**Comment by mrsudarshanrai** [comment]
@ashiishme Hey, I will be happy to take over this issue.

**Comment by ashiishme** [comment]
@mrsudarshanrai  Thank you.

**Comment by sharunspi** [comment]
> @ashiishme Hey, I will be happy to take over this issue.

I was busy with other works. please takeover . Thanks
